brew "git"
brew "ollama"
brew "aider"
brew "colima"

cask "ghostty"
cask "raycast"
cask "karabiner-elements"
cask "hammerspoon"
cask "superwhisper"
cask "font-jetbrains-mono-nerd-font"
cask "hiddenbar"
cask "blurred"
cask "espanso"
cask "arc"
cask "slack"
cask "cursor"
cask "figma"
# cask "docker"
cask "shottr"
cask "chatgpt"
cask "spotify"
cask "craft" 
cask "whatsapp"